version: '3.8'

services:
  orchestrator:
    build: .
    container_name: ai-upgrader-orchestrator
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - ANALYZER_SERVICE_URL=${ANALYZER_SERVICE_URL:-http://analyzer:8001}
      - BUILDER_SERVICE_URL=${BUILDER_SERVICE_URL:-http://builder:8002}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - ai-upgrader-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '1'
        reservations:
          memory: 512MB
          cpus: '0.5'

networks:
  ai-upgrader-network:
    driver: bridge