[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci --include=dev']

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
HOSTNAME = '0.0.0.0'